project:
  type: website

website:
  title: "ISSS608-First"
  navbar:
    left: 
    - text: "Hands-on Exercise"
      menu: 
      - text: "1. A Layered Grammar of Graphics: ggplot2 methods"
        href: "exercises/HE01.html"
      - text: "2. Beyond ggplot2 Fundamentals"
        href: "exercises/HE02.html"
      - text: "3a. Programming Interactive Data Visualisation with R"
        href: "exercises/HE03.html"
      - text: "3b. Programming Animated Statistical Graphics with R"
        href: "exercises/HE03b.html"
      - text: "4a. Visualising Distribution"
        href: "exercises/HE04a.html"
      - text: "4b. Visual Statistical Analysis"
        href: "exercises/HE04b.html"
      - text: "4c. Visualising Uncertainty"
        href: "exercises/HE04c.html"
      - text: "4d. Funnel Plots for Fair Comparisons"
        href: "exercises/HE04d.html"
    - text: "In-class Exercise"
      menu:
      - text: "In-class Exercise 1"
        href: "https://public.tableau.com/app/profile/nazia.faruqui/viz/In-class_Ex01_17686351432730/Dashboard1"
      - text: "In-class Exercise 2"
        href: "https://public.tableau.com/app/profile/nazia.faruqui/viz/In-class_Ex02_17692383170620/Dashboard2"
      - text: "In-class Exercise 3"
        href: "https://public.tableau.com/app/profile/nazia.faruqui/viz/In-classExercise3_17698443972940/In-class_Ex03"
    right:
      - href: index.qmd
        text: Home
      - href: about.qmd
        text: About Me

format:
  html:
    theme:
      - cosmo
      - brand
    fontsize: 1.3em
    css: styles.css
    page-layout: full
    toc: true
    toc-location: left
    grid: 
      sidebar-width: 250px
      body-width: 1300px
      margin-width: 60px
      gutter-width: 20px

editor: visual
