project:
  type: website

website:
  title: "ISSS608-First"
  navbar:
    left: 
    - text: "Hands-on Exercise"
      menu: 
      - text: "1. A Layered Grammar of Graphics: ggplot2 methods"
        href: "HE01.html"
      - text: "2. Beyond ggplot2 Fundamentals"
        href: "HE02.html"
      - text: "3a. Programming Interactive Data Visualisation with R"
        href: "HE03.html"
      - text: "3b. Programming Animated Statistical Graphics with R"
        href: "HE03b.html"  
    - text: "In-class Exercise"
      menu:
      - text: "In-class Exercise 1"
        href: "IE01.html"
    right:
      - href: index.qmd
        text: Home
      - about.qmd

format:
  html:
    theme:
      - cosmo
      - brand
    fontsize: 1.3em
    css: styles.css
    page-layout: full
    toc: true
    toc-location: left
    grid: 
      sidebar-width: 250px
      body-width: 1300px
      margin-width: 60px
      gutter-width: 20px

editor: visual
